name: demo-application
run-name: ${{ github.actor }} Running Demo Application
on: 
  push:
    branches:    
      - main
    tags:        
      - v2
      - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Sonar Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd demo/
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=khanMuhtashim007_sada-pay-cicd
  deploy_staging:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    environment: 'staging'
    needs: build
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set Release Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # - name: Test stage
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{ env.RELEASE_VERSION }}
      - name: Docker Build
        run: |
          cd demo/
          docker build . -t muhtashim/muhtashim-maven:${{ env.RELEASE_VERSION }}
          docker push muhtashim/muhtashim-maven:${{ env.RELEASE_VERSION }}
      # - name: Docker Push
      #   run: |
      #     docker push muhtashim/muhtashim-maven:${{ env.RELEASE_VERSION }}
      - name: Run Application
        run: |
          docker run -itd -p 8080:8080 muhtashim/muhtashim-maven:${{ env.RELEASE_VERSION }}
  deploy_prod:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    environment: 'production'
    needs: [build, deploy_staging]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Application
        run: |
          docker run -itd -p 8080:8080 muhtashim/muhtashim-maven:${{ env.RELEASE_VERSION }}


